export interface Business {
  id?: string
  slug: string
  name: string
  niche?: string
  template_key?: string
  phone?: string
  phone_carrier_type?: string
  email1?: string
  email1_status?: string
  addr1?: string
  city?: string
  state?: string
  postal?: string
  country?: string
  latitude?: number
  longitude?: number
  rating?: number
  reviews?: number
  reviews_link?: string
  logo?: string
  logo_good?: boolean
  hero_image?: string
  about_image?: string
  facebook?: string
  instagram?: string
  linkedin?: string
  tiktok?: string
  primary_color?: string
  secondary_color?: string
  site?: string
  category?: string
  about?: string
  description?: string
  verified?: boolean
  place_id?: string
  photos_count?: number
  working_hours?: Record<string, string>
  booking_appointment_link?: string
  website_generator?: string
  website_description?: string
  website_has_facebook_pixel?: boolean
  website_has_google_pixel?: boolean
  email2?: string
  email2_status?: string
  email3?: string
  email3_status?: string
  phone2?: string
  phone3?: string
  business_status?: string
  created_at?: string
  updated_at?: string
  image_overrides?: {
    logo?: string
    hero?: string
    about?: string
  }
}
